name: i_dont_remember
description: "Have you ever found yourself struggling to remember how long ago you opened your carton of milk to check if it was still good? Or maybe you can't recall the last time you dusted your room? Have you ever misplaced a high school book and couldn't remember where you put it? If any of these situations sound familiar, why not give this app a try?"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  json_annotation: ^4.8.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  shimmer: ^3.0.0
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2
  firebase_core: ^2.27.2
  cloud_firestore: ^4.15.10
  firebase_auth: ^4.18.0
  firebase_storage: ^11.6.11
  flutter_svg: ^2.0.10+1
  flutter_markdown: ^0.6.22
  google_sign_in: ^6.2.1
  tuple: ^2.0.2

dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
